// GENERATED BY CURSOR (strict) — changed Phase 1 on 2025-09-30. ASSUMPTION: Only UPI enabled.

import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';

class PaymentMethodsScreen extends StatelessWidget {
  const PaymentMethodsScreen({super.key});

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);
    return Material(
      color: const Color.fromARGB(255, 255, 255, 255),
      child: SafeArea(
        child: ListView(
        padding: const EdgeInsets.all(16),
        children: [
          Row(
            children: [
              IconButton(
                icon: const Icon(Icons.arrow_back),
                onPressed: () => Navigator.of(context).maybePop(),
              ),
              const SizedBox(width: 8),
              Text('Choose your payment method', style: theme.textTheme.titleMedium),
            ],
          ),
          const SizedBox(height: 12),
          _MethodTile(
            icon: Icons.account_balance_wallet,
            title: 'UPI',
            enabled: true,
            onTap: () => context.push('/dashboard/subscription/upi'),
          ),
          const SizedBox(height: 8),
          _MethodTile(
            icon: Icons.credit_card, 
            title: 'Debit / Credit Card', 
            enabled: true,
            onTap: () => context.push('/dashboard/subscription/payment/card'),
          ),
          const SizedBox(height: 8),
          _MethodTile(
            icon: Icons.account_balance, 
            title: 'Net Banking', 
            enabled: true,
            onTap: () => context.push('/dashboard/subscription/payment/netbanking'),
          ),
          const SizedBox(height: 8),
          _MethodTile(
            icon: Icons.account_box, 
            title: 'Bank Transfer', 
            enabled: true,
            onTap: () => context.push('/dashboard/subscription/payment/transfer'),
          ),
        ],
        ),
      ),
    );
  }
}

class _MethodTile extends StatelessWidget {
  const _MethodTile({required this.icon, required this.title, this.enabled = true, this.onTap});
  final IconData icon;
  final String title;
  final bool enabled;
  final VoidCallback? onTap;

  @override
  Widget build(BuildContext context) {
    return ListTile(
      leading: Icon(icon),
      title: Text(title),
      trailing: const Icon(Icons.chevron_right),
      enabled: enabled,
      onTap: enabled ? onTap : null,
      shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12)),
      tileColor: Theme.of(context).colorScheme.surface,
    );
  }
}


